labels: Idea, Needs review
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your idea
      description: How can Weather VN be improved? Suggest only one idea at a time (open a new issue for a different idea).
      placeholder: |
        Example:
          "Here is how it should work: …"
    validations:
      required: true

  - type: textarea
    id: other-details
    attributes:
      label: Other details
      placeholder: |
        Additional details and attachments.

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Your issue will be closed if you don’t read this carefully.
      options:
        - label: I have searched the [existing issues](https://github.com/wikiepeidia/vn-weather-with-locationiq-and-nominatim/issues) and this is a new ticket, **NOT** a duplicate or related to another open OR closed issue.
          required: true
        - label: I have updated the app to the **[latest release](https://github.com/wikiepeidia/vn-weather-with-locationiq-and-nominatim/releases)**.
          required: true
          required: true
        - label: I wrote my request in English, and any screenshot I attached are also in English (language can be changed from Settings > Appearance). I can write in my native language under the English text, if necessary.
          required: true
        - label: I understand that this app is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY, so I may not get a positive reply to my request, if any at all.
          required: true
