blank_issues_enabled: true
contact_links:
  - name: Questions / Ideas
    url: https://github.com/wikiepeidia/vn-weather-with-locationiq-and-nominatim/issues
    about: Ask questions or suggest improvements
